### root

http://localhost:5000/api/

### video info

http://localhost:5000/api/info?l=https://www.youtube.com/watch?v=JtH68PJIQLE

### mount resource

http://localhost:5000/api/mount?r=v&l=https://www.youtube.com/watch?v=JtH68PJIQLE
