### root

http://localhost:5000/api/

### video info

http://localhost:5000/api/info?l=https://www.youtube.com/watch?v=JtH68PJIQLE

### mount video resource

http://localhost:5000/api/mount?l=https://www.youtube.com/watch?v=JtH68PJIQLE&r=v

### mount audio resource

http://localhost:5000/api/mount?l=https://www.youtube.com/watch?v=JtH68PJIQLE&r=a

### mount music resource

http://localhost:5000/api/mount?l=https://www.youtube.com/watch?v=JtH68PJIQLE&r=m

### download ticket resource

http://localhost:5000/api/download?t=818e1cf9-b253-4a87-941d-bc066f645a85
